# Site
name: "Jashn-e-Rag"
title: "Shuchshmita ki Jashn-e-Rag"
description: "Kahaniya aur Kavitayein"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-163943876-2'
disqus: 'jashn-e-rag'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  suchi:
    name: Shuchshmita
    display_name: Shuchshmita
    gravatar: shuchishmita
    email: shwetagoswami28595@gmail.com
    web: https://www.facebook.com/profile.php?id=100009478474232
    twitter: https://www.instagram.com/shweta_goswameee/
    description: "Author of  Jashn-e-Rag, Delhi University and Indra Gandhi National Open University  Alumni and a Civil Service Aspirant"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
#adsense: "disabled"
#adsense-data-ad-client: "ca-pub-3412143450191416"
#adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
